### ISSUE TITLE
Failed to create VirtualBox client! rc = 0x80004002

### ISSUE THREAD

**Issue by slavashvets** [Waterflames/VBoxRecorder#1]
It doesn't work.

**Environment:**
Windows 8.1 64Bit
VirtualBox 5.0.14 r105127
VBoxRecorder 1.0.0-alpha

**Steps to reproduce:**
1. Start VM
2. Open cmd as administrator
3. Change working dir into unpacked VBoxRecorder folder
4. Run "VBoxRecorder.exe"

**Expected**:
Running

**Actual**:

```
Connecting to the VirtualBox Service...
Failed to create VirtualBox client! rc = 0x80004002
```

**Comment by Wouterdek** [comment]
Fixed by commit 915e45a
