### ISSUE TITLE
Failed to read framebuffer! errorcode=12b

### ISSUE THREAD

**Issue by slavashvets** [Waterflames/VBoxRecorder#2]
Hello again. Thanks for the fast fixing of #1 . 

I still can't start recording:
##### Environment

Windows 7 64Bit
VirtualBox 5.0.14 r105127
VBoxRecorder 1.0.1-alpha

_The target VM is in full screen mode with standard 1280x720 resolution._
##### Steps to reproduce
1. Start VM
2. Open cmd as user
3. Change working dir into unpacked VBoxRecorder folder
4. Run "VBoxRecorder.exe"
5. Do:
   
   ```
   C:\Users\vshvets\Downloads\Release>VBoxRecorder.exe
   VBoxRecorder for VirtualBox 5.0.14 r105127 Windows 64-bit
   Connecting to the VirtualBox Service...
   Connected and ready! Use 'help' for a list of commands.
   >machines
   5 virtual machines found:
    [0] ONLINE  {name = "W1 Lubuntu 12.10", id="5015171f-83ae-4a40-a375-fa56822d449
    [1] OFFLINE {name = "boot2docker-vm", id="af2b4fbb-7604-4a7d-8cc5-df44a6388005"
    [2] OFFLINE {name = "trackr-vagrant_default_1446734415625_81248", id="7a26f7c8-
    [3] ONLINE  {name = "default", id="684f92e8-f1e4-471b-aa56-2f09042000da"}
    [4] ONLINE  {name = "wini81", id="231457bd-8515-410a-adf1-b7b2e697edb3"}
   >select 4
   Machine 231457bd-8515-410a-adf1-b7b2e697edb3 was selected.
   >outputfile test.avi
   Output file set to: test.avi
   >record
   Retrieving VM info
   Retrieving VM process info
   Elevating privileges to read VM process memory
   ```
6. Accept Elevating privileges
##### Expected

Record started
##### Actual

```
VBoxRecorder for VirtualBox 5.0.14 r105127 Windows 64-bit
Searching framebuffer pointer in process 18516
Found framebuffer at 0x00000000002E6874
[huffyuv @ 0000000000144240] using huffyuv 2.2.0 or newer interlacing flag

Press ESC to stop recording
Failed to read framebuffer! errorcode=12b
Press enter to continue
```

**Comment by Wouterdek** [comment]
It seems it is still not finding the correct framebuffer offset. Would it be possible for you to provide me with a full dump of the virtualbox process? (Don't do this if the VM contains sensitive information.)

Just download the ProcDump tool (technet.microsoft.com/en-us/sysinternals/dd996900.aspx),
open cmd in the procdump folder and run "procdump -ma PID" where PID is the number that VBoxRecorder displays in its line "Searching framebuffer pointer in process PID".
The resulting file will be multiple GB, but after zipping it will be a couple hunderds of MB big.

**Comment by slavashvets** [comment]
There's no sensitive data, it's just blank Microsoft VM for testing IE. Please feel free to [download the dump](https://yadi.sk/d/F28soBq3orVhq?ncrnd=0152) any time. Thanks.

**Comment by Wouterdek** [comment]
Please try the latest version. Make sure to read the release notes for optimal performance.

**Comment by slavashvets** [comment]
It works. Thank you very much!
